name: Deno

on:
  pull_request:
    branches: [develop, master]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [macOS-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Cache Dependencies
        run: deno cache cli.ts

      - name: Run Tests
        run: deno test -A --unstable
