name: Deno

on:
  push:
    branches: [master]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@c7d7968ad4a59c159a777f79adddad6872ee8d96
        with:
          deno-version: ${{ matrix.deno }}

      - name: Cache Dependencies
        run: deno cache cli.ts

      - name: Run Tests
        run: deno test -A --unstable
